language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm run coverage -- -u

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

